In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
%cd /content/drive/MyDrive

/content/drive/MyDrive

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt

In [5]:
import os
os.chdir("/content/drive/MyDrive/car-insurance-claim-prediction")

In [6]:
!pwd

/content/drive/MyDrive/car-insurance-claim-prediction

In [7]:
import pandas as pd

train = pd.read_csv("data/raw/train.csv")
test = pd.read_csv("data/raw/test.csv")
sample = pd.read_csv("data/raw/sample_submission.csv")

train.shape, test.shape, sample.shape

((58592, 44), (39063, 43), (39063, 2))

In [8]:
train.head()

,policy_id,policy_tenure,age_of_car,age_of_policyholder,area_cluster,population_density,make,segment,model,fuel_type,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,is_claim
0,ID00001,0.515874,0.05,0.644231,C1,4990,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
1,ID00002,0.672619,0.02,0.375000,C2,27003,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
2,ID00003,0.841110,0.02,0.384615,C3,4076,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
3,ID00004,0.900277,0.11,0.432692,C4,21622,1,C1,M2,Petrol,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0
4,ID00005,0.596403,0.11,0.634615,C5,34738,2,A,M3,Petrol,...,No,Yes,Yes,Yes,No,Yes,Yes,Yes,2,0

In [9]:
train.columns

Index(['policy_id', 'policy_tenure', 'age_of_car', 'age_of_policyholder',
       'area_cluster', 'population_density', 'make', 'segment', 'model',
       'fuel_type', 'max_torque', 'max_power', 'engine_type', 'airbags',
       'is_esc', 'is_adjustable_steering', 'is_tpms', 'is_parking_sensors',
       'is_parking_camera', 'rear_brakes_type', 'displacement', 'cylinder',
       'transmission_type', 'gear_box', 'steering_type', 'turning_radius',
       'length', 'width', 'height', 'gross_weight', 'is_front_fog_lights',
       'is_rear_window_wiper', 'is_rear_window_washer',
       'is_rear_window_defogger', 'is_brake_assist', 'is_power_door_locks',
       'is_central_locking', 'is_power_steering',
       'is_driver_seat_height_adjustable', 'is_day_night_rear_view_mirror',
       'is_ecw', 'is_speed_alert', 'ncap_rating', 'is_claim'],
      dtype='object')

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 44 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   policy_id                         58592 non-null  string
 1   policy_tenure                     58592 non-null  float64
 2   age_of_car                        58592 non-null  float64
 3   age_of_policyholder               58592 non-null  float64
 4   area_cluster                      58592 non-null  string
 5   population_density                58592 non-null  int64
 6   make                              58592 non-null  int64
 7   segment                           58592 non-null  category
 8   model                             58592 non-null  category
 9   fuel_type                         58592 non-null  category
 10  max_torque                        58592 non-null  string
 11  max_power                         58592 non-null  string
 12  engine_type                       58592 non-null  category
 13  airbags                           58592 non-null  int64
 14  is_esc                            58592 non-null  object
 15  is_adjustable_steering            58592 non-null  bool
 16  is_tpms                           58592 non-null  bool
 17  is_parking_sensors                58592 non-null  bool
 18  is_parking_camera                 58592 non-null  bool
 19  rear_brakes_type                  58592 non-null  category
 20  displacement                      58592 non-null  int64
 21  cylinder                          58592 non-null  int64
 22  transmission_type                 58592 non-null  category
 23  gear_box                          58592 non-null  int64
 24  steering_type                     58592 non-null  category
 25  turning_radius                    58592 non-null  float64
 26  length                            58592 non-null  int64
 27  width                             58592 non-null  int64
 28  height                            58592 non-null  int64
 29  gross_weight                      58592 non-null  int64
 30  is_front_fog_lights               58592 non-null  bool
 31  is_rear_window_wiper              58592 non-null  bool
 32  is_rear_window_washer             58592 non-null  bool
 33  is_rear_window_defogger           58592 non-null  bool
 34  is_brake_assist                   58592 non-null  bool
 35  is_power_door_locks               58592 non-null  bool
 36  is_central_locking                58592 non-null  bool
 37  is_power_steering                 58592 non-null  bool
 38  is_driver_seat_height_adjustable  58592 non-null  bool
 39  is_day_night_rear_view_mirror     58592 non-null  bool
 40  is_ecw                            58592 non-null  bool
 41  is_speed_alert                    58592 non-null  bool
 42  ncap_rating                       58592 non-null  int64
 43  is_claim                          58592 non-null  int64
dtypes: bool(16), category(7), float64(4), int64(12), object(1), string(4)
memory usage: 10.7+ MB

In [ ]:
train[['policy_id',
'area_cluster',
'segment',
'model',
'fuel_type',
'max_torque',
'max_power',
'engine_type',
'is_adjustable_steering',
'is_tpms',
'is_parking_sensors',
'is_parking_camera']].head(4)

,policy_id,area_cluster,segment,model,fuel_type,max_torque,max_power,engine_type,is_adjustable_steering,is_tpms,is_parking_sensors,is_parking_camera
0,ID00001,C1,A,M1,CNG,60Nm@3500rpm,40.36bhp@6000rpm,F8D Petrol Engine,True,True,True,True
1,ID00002,C2,A,M1,CNG,60Nm@3500rpm,40.36bhp@6000rpm,F8D Petrol Engine,True,True,True,True
2,ID00003,C3,A,M1,CNG,60Nm@3500rpm,40.36bhp@6000rpm,F8D Petrol Engine,True,True,True,True
3,ID00004,C4,C1,M2,Petrol,113Nm@4400rpm,88.50bhp@6000rpm,1.2 L K12N Dualjet,True,True,True,True

In [ ]:
'''obj ->
policy_id,
area_cluster,
segment,
model,
fuel_type,
max_torque,
max_power,
engine_type,
is_adjustable_steering,
is_tpms ,
is_parking_sensors,
is_parking_camera,
rear_brakes_type,
transmission_type ,
steering_type ,
is_front_fog_lights ,
is_rear_window_wiper,
is_rear_window_washer,
is_rear_window_defogger ,
is_brake_assist ,
is_power_door_locks,
is_central_locking,
is_power_steering ,
is_driver_seat_height_adjustable,
is_day_night_rear_view_mirror,
is_ecw ,
is_speed_alert          '''

'obj -> \npolicy_id,\narea_cluster, \nsegment,                            \nmodel,                             \nfuel_type,             \nmax_torque,                       \nmax_power,                 \nengine_type,                  \nis_adjustable_steering,         \nis_tpms ,                      \nis_parking_sensors,            \nis_parking_camera,     \nrear_brakes_type,\ntransmission_type ,       \nsteering_type ,\nis_front_fog_lights ,     \nis_rear_window_wiper,      \nis_rear_window_washer,  \nis_rear_window_defogger ,  \nis_brake_assist ,  \nis_power_door_locks,  \nis_central_locking,   \nis_power_steering ,       \nis_driver_seat_height_adjustable,\nis_day_night_rear_view_mirror,   \nis_ecw ,           \nis_speed_alert          '

In [ ]:
train[['rear_brakes_type',
'transmission_type' ,
'steering_type' ,
'is_front_fog_lights' ,
'is_rear_window_wiper',
'is_rear_window_washer',
'is_rear_window_defogger' ,
'is_brake_assist' ,
'is_power_door_locks',
'is_central_locking',
'is_power_steering' ,
'is_driver_seat_height_adjustable',
'is_day_night_rear_view_mirror',
'is_ecw' ,
'is_speed_alert']].head(4)

,rear_brakes_type,transmission_type,steering_type,is_front_fog_lights,is_rear_window_wiper,is_rear_window_washer,is_rear_window_defogger,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert
0,Drum,Manual,Power,True,True,True,True,True,True,True,True,True,True,True,True
1,Drum,Manual,Power,True,True,True,True,True,True,True,True,True,True,True,True
2,Drum,Manual,Power,True,True,True,True,True,True,True,True,True,True,True,True
3,Drum,Automatic,Electric,True,True,True,True,True,True,True,True,True,True,True,True

In [ ]:
train[['rear_brakes_type',
'transmission_type' ,
'steering_type' ,
'is_front_fog_lights' ,
'is_rear_window_wiper',
'is_rear_window_washer',
'is_rear_window_defogger' ,
'is_brake_assist' ,
'is_power_door_locks',
'is_central_locking',
'is_power_steering' ,
'is_driver_seat_height_adjustable',
'is_day_night_rear_view_mirror',
'is_ecw' ,
'is_speed_alert']].nunique()

rear_brakes_type                    2
transmission_type                   2
steering_type                       3
is_front_fog_lights                 1
is_rear_window_wiper                1
is_rear_window_washer               1
is_rear_window_defogger             1
is_brake_assist                     1
is_power_door_locks                 1
is_central_locking                  1
is_power_steering                   1
is_driver_seat_height_adjustable    1
is_day_night_rear_view_mirror       1
is_ecw                              1
is_speed_alert                      1
dtype: int64

In [ ]:
train["engine_type"].nunique()

11

In [ ]:
train["model"].nunique()

11

In [ ]:
train["segment"].nunique()

6

In [ ]:
train["engine_type"].nunique()

11

In [ ]:
train['is_adjustable_steering'].nunique()

1

In [ ]:
train['rear_brakes_type'].nunique()

2

In [ ]:
train['transmission_type'].nunique()

2

In [ ]:
c = train[['segment','model','fuel_type','engine_type','rear_brakes_type','transmission_type','steering_type'] ]

In [ ]:
b = train[['is_adjustable_steering','is_tpms' ,'is_parking_sensors','is_parking_camera','is_front_fog_lights' ,'is_rear_window_wiper', 'is_rear_window_washer','is_rear_window_defogger' ,'is_brake_assist' , 'is_power_door_locks', 'is_central_locking',  'is_power_steering' ,  'is_driver_seat_height_adjustable', 'is_day_night_rear_view_mirror', 'is_ecw' ,'is_speed_alert']]

In [ ]:
s = train[['policy_id','area_cluster','max_torque','max_power']]

In [ ]:
train.columns

Index(['policy_id', 'policy_tenure', 'age_of_car', 'age_of_policyholder',
       'area_cluster', 'population_density', 'make', 'segment', 'model',
       'fuel_type', 'max_torque', 'max_power', 'engine_type', 'airbags',
       'is_esc', 'is_adjustable_steering', 'is_tpms', 'is_parking_sensors',
       'is_parking_camera', 'rear_brakes_type', 'displacement', 'cylinder',
       'transmission_type', 'gear_box', 'steering_type', 'turning_radius',
       'length', 'width', 'height', 'gross_weight', 'is_front_fog_lights',
       'is_rear_window_wiper', 'is_rear_window_washer',
       'is_rear_window_defogger', 'is_brake_assist', 'is_power_door_locks',
       'is_central_locking', 'is_power_steering',
       'is_driver_seat_height_adjustable', 'is_day_night_rear_view_mirror',
       'is_ecw', 'is_speed_alert', 'ncap_rating', 'is_claim'],
      dtype='object')